DROP TABLE IF EXISTS `mapstable`;
CREATE TABLE IF NOT EXISTS `mapstable` (
  `record_id` int(10) unsigned NOT NULL auto_increment,
  `item_title` varchar(50) NOT NULL,
  `item_year` int(10) unsigned NOT NULL,
  `item_description` text NOT NULL,
  `item_image` varchar(100) default NULL,
  PRIMARY KEY  (`record_id`)
) ENGINE=MyISAM AUTO_INCREMENT=7 DEFAULT CHARSET=latin1 AUTO_INCREMENT=7 ;

-- 
-- Dumping data for table `mapstable`
-- 

INSERT INTO `mapstable` (`record_id`, `item_title`, `item_year`, `item_description`, `item_image`) VALUES (1, 'Capitol Park', 1832, 'Capitol Park was constructed alongside the State House. It is a large, open green with tree-lined paths and is home to several monuments, including those for the Civil War, World War I and the Vietnam War.\r\n\r\nCapitol Park is the home for many prominent regional and state events, including the annual United Bikers Of Maine Toy Run and the Kennebec Valley Chamber of Commerce''s "Day In The Park," which is the offspring of the former Whatever Week festival.\r\n\r\nCapitol Park was renovated as part of the State House / State Office Building renovations in the late 1990s.', NULL),
(2, 'State House', 1832, 'Maine''s State House was designed by the famous Charles Bullfinch, who also designed the Massachusetts State House (Maine was, until 1820, part of Massachusetts).\r\n\r\nIt received major redesigns in 1852, 1860, 1890 and 1909, when the dome was added. Although the grounds and building interior have been renovated extensively inside since then, most notably in 2000, the State House appears fundamentally the same from the outside now as it did in 1910.\r\n\r\nThe State House includes the offices of the Legislature and the governor.\r\n\r\n<em><a href="http://en.wikipedia.org/wiki/Maine_State_House">Read the Wikipedia entry for the Maine State House</a>. Image from Wikipedia, used under GNU License.</em>', 'statehouse.jpg'),
(3, 'Burton M. Cross State Office Building', 1950, 'The Burton M. Cross State Office Building is where most of the central business of the state is conducted.\r\n\r\nIt''s one of Augusta''s tallest buildings, at five floors (not including the basement floors) and is attached to the State House via an underground tunnel.\r\n\r\nThe building is not that attractive and blocks the view of the State House from the West. It was extensively renovated in 2000.', NULL),
(4, 'Blaine House / Governor''s Mansion', 1833, 'The Blaine House has had many owners over the years. Built by Captain James Hall and once owned by legendary Gov. James Blaine (the founder of Baxter State Park), it was donated by his family to be the governor''s official residence in 1919.\r\n\r\nThe residence is currently occupied by Gov. John Baldacci and his family; however, Baldacci''s predecessor, Angus King, and his family did not live in the residence.\r\n\r\n<em><a href="http://www.blainehouse.org/">Visit the official Blaine House Web site</a></em>', 'http://www.blainehouse.org/images/new/The_Blaine_House_pic.jpg'),
(5, 'Cultural Building', 1971, 'The Cultural Building houses the Maine State Library, Maine State Museum and the Maine State Archives. \r\n\r\nSignificant renovations of the facility are currently in the planning stages.\r\n\r\n<em>Visit the <a href="http://www.maine.gov/msl/">Maine State Library</a>, <a href="http://www.maine.gov/museum/">Maine  State Library</a> and <a href="http://www.maine.gov/sos/arc/">Maine State Archives</a> official Web sites</em>', NULL),
(6, 'Vietnam Veterans War Memorial', 1985, 'This monument features several triangular structures with cut-out silhouettes of Vietnam soldiers.\r\n\r\nThe monument was controversial; the Maine Legislature''s Executive Council, made up of legislative leadership and which has oversight of Capitol Park, is generally reluctant to base memorials in the park. (There are many memorials located around the State House grounds, including memorials to firefighters, police officers and <a href="http://en.wikipedia.org/wiki/Samantha_Smith">Samantha Smith</a>, who was noteworthy during the Cold War.\r\n\r\nThe only other war memorial in Capitol Park dates to just after the Civil War.', 'memorial.jpg');
